LITC\VideoPlayerBundle\Entity\Video:
    type: mappedSuperclass
    repositoryClass: VideoRepository
    table: video
    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        videoId:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        videoServer:
            type: integer
            nullable: false
        thumb:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
