Lifeinthecloud\VideoPlayerBundle\Entity\Video:
    type: mappedSuperclass
    repositoryClass: VideoRepository
    table: video
    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        videoId:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    oneToOne:
        videoServer:
            targetEntity: VideoServer
            joinColumn:
                name: video_server_id
                referencedColumnName: id
            cascade: ["persist"]
    lifecycleCallbacks: {  }
