Lifeinthecloud\VideoPlayerBundle\Entity\Video:
    type: entity
    repositoryClass: VideoRepository
    table: video
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        video_id:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    oneToOne:
        videoServer:
            targetEntity: VideoServer
            joinColumn:
                name: video_server_id
                referencedColumnName: id
            cascade: ["persist"]
    lifecycleCallbacks: {  }
