Lifeinthecloud\VideoPlayerBundle\Entity\VideoServer:
    type: entity
    table: video_server
    repositoryClass: VideoServerRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
