services:
    lifeinthecloud_video_player.video_manager.default:
        class: Lifeinthecloud\VideoPlayerBundle\Doctrine\VideoManager
        arguments: ["security.encoder_factory", "lifeinthecloud_video_player.entity_manager", "%lifeinthecloud_video_player.model.video.class%"]

    lifeinthecloud_video_player.entity_manager:
        factory-service: doctrine
        factory-method: getManager
        class: Doctrine\ORM\EntityManager
        arguments: ["%lifeinthecloud_video_player.model_manager_name%"]