services:
    lifeinthecloud_video_player.video_player_service:
        class: Lifeinthecloud\VideoPlayerBundle\Service\VideoPlayerService
    lifeinthecloud_video_player.parser_service:
        class: Lifeinthecloud\VideoPlayerBundle\Service\ParserService

    lifeinthecloud_video_player.twig.video_player_extension:
        class: Lifeinthecloud\VideoPlayerBundle\Twig\VideoPlayerExtension
        arguments: ["@lifeinthecloud_video_player.video_player_service"]
        tags:
            - { name: twig.extension }