services:
    litc_video_player.video_player_service:
        class: LITC\VideoPlayerBundle\Service\VideoPlayerService
    litc_video_player.parser_service:
        class: LITC\VideoPlayerBundle\Service\ParserService