services:
    lifeinthecloud_video_player.service:
        class: Lifeinthecloud\VideoPlayerBundle\Service\VideoPlayerService

    lifeinthecloud_video_player.twig.video_player_extension:
        class: Lifeinthecloud\VideoPlayerBundle\Twig\VideoPlayerExtension
        arguments: ["@lifeinthecloud_video_player.service"]
        tags:
            - { name: twig.extension }