services:
    litc_video_player.video.form:
        factory-method: createNamed
        factory-service: form.factory
        class: Symfony\Component\Form\Form
        arguments: 
            - "%litc_video_player.video.form.name%"
            - "%litc_video_player.video.form.type%"
        
        
    litc_video_player.video.form.type:
        class: LITC\VideoPlayerBundle\Form\Type\VideoFormType
        arguments:
            - "%litc_video_player.model.video.class%"
        tags:
            -  { name: form.type, alias: litc_video_player_video }

    litc_video_player.video.form.handler.default:
        class: LITC\VideoPlayerBundle\Form\Handler\VideoFormHandler
        scope: request
        public: false
        arguments:
            - "litc_video_player.profile.form"
            - "request"
            - "litc_video_player.video_manager"